spring:
    datasource:
        url: jdbc:mysql://localhost:3306/library-management?characterEncoding=utf-8&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: unsafe0128
server:
    port: 9090

mybatis:
    mapper-locations: classpath:mapper/*.xml
